name: Required Status Checks
description: Monitor required status checks matching a regex pattern
author: John Zammit

branding:
  icon: check-circle
  color: green

inputs:
  status-regex:
    description: 'Regex pattern to match status check names'
    required: true
  expected-checks:
    description: 'Number of expected checks to match'
    required: true
    default: '1'

runs:
  using: node20
  main: dist/index.js
